on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v4.1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: build
        run: |
          idf.py build
          cp build/partition_table/partition-table.bin .
          cp build/bootloader/bootloader.bin .
          cp build/uthar.bin .
          tar -czvf uthar.tar.gz partition-table.bin bootloader.bin uthar.bin

      - uses: actions/upload-artifact@v2
        with:
          name: uthar.tar.gz
          path: uthar.tar.gz
          if-no-files-found: error

  publish:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: uthar.tar.gz
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          name: nightly
          prerelease: true
          allow_override: true
          body: |
            This is an auto-generated release from the last successful build
            Unzip this file into the 3 `.bin` files then
            see the README for instructions to flash
          gzip: folders
          files: >
            uthar.tar.gz
